services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: my-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

volumes:
  db-data: